## First Operation

In [2]:
import numpy as np 

arr = np.arange(1,21)
print("Original Array is: ",arr)
print("Additional of Array is: ",np.sum(arr))
print("Mean of Array is:",np.mean(arr))
print("Meadian of Array is: ", np.median(arr))
print("Standard Derivation of Array is: ", np.std(arr))

print()

print("The Element Greater than 10 in array is: ", arr[arr > 10])


Original Array is:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Additional of Array is:  210
Mean of Array is: 10.5
Meadian of Array is:  10.5
Standard Derivation of Array is:  5.766281297335398

The Element Greater than 10 in array is:  [11 12 13 14 15 16 17 18 19 20]


## Second Operation

In [3]:
arr_2d = np.arange(1,17).reshape(4,4)
print("2D Array is: ",arr_2d)

print()

print("Transpose of 2D Array is: ", arr_2d.T)

print()

print("Row Wise Calculation of 2D Array is: ", arr_2d.sum(axis = 1))
print("Column Wise Calculation of 2D Array is: ", arr_2d.sum(axis = 0))

2D Array is:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose of 2D Array is:  [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row Wise Calculation of 2D Array is:  [10 26 42 58]
Column Wise Calculation of 2D Array is:  [28 32 36 40]


## Third Operation

In [4]:
arr_a = np.random.randint(1, 21, (3,3))
arr_b = np.random.randint(1, 21, (3,3))
print("Array A is: ", arr_a)
print("Array B is: ", arr_b)

print()

print("Adittion of Array A and Array B is: ", arr_a + arr_b)
print("Subtraction of Array A and Array B is: ", arr_a - arr_b)
print("Multiplication of Array A and Array B is: ", arr_a * arr_b)

print()

print("Dot Product of Array A and Array B is: ", arr_a.dot(arr_b))

Array A is:  [[ 8  2 12]
 [18  5  3]
 [ 6  4  6]]
Array B is:  [[10  3 10]
 [ 4 16 17]
 [10 19 12]]

Adittion of Array A and Array B is:  [[18  5 22]
 [22 21 20]
 [16 23 18]]
Subtraction of Array A and Array B is:  [[ -2  -1   2]
 [ 14 -11 -14]
 [ -4 -15  -6]]
Multiplication of Array A and Array B is:  [[ 80   6 120]
 [ 72  80  51]
 [ 60  76  72]]

Dot Product of Array A and Array B is:  [[208 284 258]
 [230 191 301]
 [136 196 200]]


## Fourth Operation

In [6]:
arr_1d = np.arange(1,13)
print("1D Array is :", arr_1d)

print()

new_arr = arr_1d.reshape(3,4)
print("Reshaped Array is: ", new_arr)

print()

slice = new_arr[:2,-2:]
print("Array after slicing first two rows and last two columns is: ", slice)

1D Array is : [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array is:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array after slicing first two rows and last two columns is:  [[3 4]
 [7 8]]
